services:
  frontend:
    build:
      context: ./builds/angular
    working_dir: /app
    volumes:
      - ./src:/app
  backend:
    build:
      context: ./builds/nestjs
    working_dir: /app
    volumes:
      - ./src/backend:/app