services:
  frontend:
    build:
      context: ./builds/angular
    command: ['node', 'index.js']
    working_dir: /app
    volumes:
      - ./src/frontend:/app
  backend:
    build:
      context: ./builds/nestjs
    command: ['node', 'index.js']
    working_dir: /app
    volumes:
      - ./src/backend:/app